#:schema node_modules/wrangler/config-schema.json

# aSpiral - Cloudflare Pages deployment
name = "aspiral"
main = "src/worker.ts"
pages_build_output_dir = "dist"
compatibility_date = "2025-03-01"

[assets]
directory = "./dist"
